CREATE TABLE `abTestResults` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`testName` varchar(255) NOT NULL,
	`contentTemplateId` int NOT NULL,
	`versionAId` int NOT NULL,
	`versionBId` int NOT NULL,
	`additionalVersionIds` json,
	`primaryMetric` enum('ctr','conversion_rate','engagement','revenue') DEFAULT 'ctr',
	`minimumSampleSize` int DEFAULT 100,
	`confidenceThreshold` decimal(5,4) DEFAULT '0.95',
	`winnerVersionId` int,
	`winnerDeclaredAt` timestamp,
	`winnerDeclaredBy` enum('auto','manual'),
	`statisticalSignificance` decimal(5,4),
	`confidenceLevel` decimal(5,4),
	`uplift` decimal(10,4),
	`status` enum('running','paused','completed','inconclusive') DEFAULT 'running',
	`startedAt` timestamp NOT NULL DEFAULT (now()),
	`endedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `abTestResults_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `contentSchedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`savedTemplateId` int NOT NULL,
	`contentTemplateId` int,
	`frequency` enum('daily','weekly','biweekly','monthly') NOT NULL,
	`dayOfWeek` int,
	`dayOfMonth` int,
	`timeOfDay` varchar(8),
	`timezone` varchar(64) DEFAULT 'UTC',
	`variables` json,
	`status` enum('active','paused','completed','failed') DEFAULT 'active',
	`lastRunAt` timestamp,
	`nextRunAt` timestamp,
	`runCount` int DEFAULT 0,
	`notifyOnComplete` boolean DEFAULT true,
	`notifyEmail` varchar(320),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `contentSchedules_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `templateShares` (
	`id` int AUTO_INCREMENT NOT NULL,
	`savedTemplateId` int NOT NULL,
	`ownerUserId` int NOT NULL,
	`sharedWithUserId` int,
	`sharedWithEmail` varchar(320),
	`permission` enum('view','duplicate','edit') DEFAULT 'view',
	`shareType` enum('direct','link','public') DEFAULT 'direct',
	`shareToken` varchar(64),
	`status` enum('pending','accepted','declined','revoked') DEFAULT 'pending',
	`viewCount` int DEFAULT 0,
	`duplicateCount` int DEFAULT 0,
	`lastAccessedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`expiresAt` timestamp,
	CONSTRAINT `templateShares_id` PRIMARY KEY(`id`)
);
