CREATE TABLE `commentLikes` (
	`id` int AUTO_INCREMENT NOT NULL,
	`commentId` int NOT NULL,
	`userId` int NOT NULL,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `commentLikes_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitorComparisons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`competitorIds` json NOT NULL,
	`dimensions` json,
	`overallScores` json,
	`recommendations` text,
	`swotAnalysis` json,
	`aiInsights` text,
	`positioningRecommendation` text,
	`isPublic` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitorComparisons_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitorContent` (
	`id` int AUTO_INCREMENT NOT NULL,
	`competitorId` int NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(512) NOT NULL,
	`contentType` enum('blog_post','video','podcast','social_post','ad','landing_page','email','webinar','case_study','whitepaper','other') NOT NULL,
	`url` text,
	`thumbnailUrl` text,
	`description` text,
	`publishedAt` timestamp,
	`views` int,
	`likes` int,
	`comments` int,
	`shares` int,
	`keyTopics` json,
	`targetKeywords` json,
	`sentiment` enum('positive','neutral','negative'),
	`qualityScore` int,
	`aiAnalysis` text,
	`contentGaps` json,
	`notes` text,
	`analyzedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitorContent_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitorProducts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`competitorId` int NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`productUrl` text,
	`imageUrl` text,
	`priceType` enum('one_time','subscription','freemium','custom','free') DEFAULT 'one_time',
	`priceMin` decimal(10,2),
	`priceMax` decimal(10,2),
	`priceCurrency` varchar(3) DEFAULT 'USD',
	`pricingNotes` text,
	`features` json,
	`uniqueSellingPoints` json,
	`targetAudience` text,
	`positioning` text,
	`comparisonToOurs` enum('better','similar','worse','different'),
	`comparisonNotes` text,
	`isActive` boolean DEFAULT true,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitorProducts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitors` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`website` varchar(512),
	`logoUrl` text,
	`industry` varchar(128),
	`category` varchar(128),
	`competitorType` enum('direct','indirect','aspirational') DEFAULT 'direct',
	`description` text,
	`tagline` text,
	`youtubeChannelId` varchar(64),
	`youtubeChannelUrl` text,
	`twitterHandle` varchar(64),
	`linkedinUrl` text,
	`instagramHandle` varchar(64),
	`foundedYear` int,
	`employeeCount` varchar(32),
	`fundingStage` varchar(64),
	`estimatedRevenue` varchar(64),
	`strengths` json,
	`weaknesses` json,
	`opportunities` json,
	`threats` json,
	`notes` text,
	`isActive` boolean DEFAULT true,
	`lastAnalyzedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitors_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `scheduleGoals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`scheduleId` int NOT NULL,
	`userId` int NOT NULL,
	`goalType` enum('improve_ctr','increase_conversions','boost_engagement','reduce_bounce','increase_revenue','grow_audience','improve_quality_score') NOT NULL,
	`targetMetric` varchar(64) NOT NULL,
	`targetValue` decimal(10,4) NOT NULL,
	`currentValue` decimal(10,4),
	`baselineValue` decimal(10,4),
	`progressPercentage` decimal(5,2) DEFAULT '0',
	`status` enum('on_track','behind','achieved','failed') DEFAULT 'on_track',
	`lastSuggestion` text,
	`suggestionGeneratedAt` timestamp,
	`deadline` timestamp,
	`achievedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `scheduleGoals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `templateComments` (
	`id` int AUTO_INCREMENT NOT NULL,
	`templateId` int NOT NULL,
	`userId` int NOT NULL,
	`content` text NOT NULL,
	`parentId` int,
	`mentionedUserIds` json,
	`likeCount` int DEFAULT 0,
	`isEdited` boolean DEFAULT false,
	`isDeleted` boolean DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `templateComments_id` PRIMARY KEY(`id`)
);
