CREATE TABLE `alertHistory` (
	`id` int AUTO_INCREMENT NOT NULL,
	`alertId` int NOT NULL,
	`userId` int NOT NULL,
	`competitorId` int NOT NULL,
	`alertType` varchar(64) NOT NULL,
	`title` varchar(512) NOT NULL,
	`message` text NOT NULL,
	`previousValue` text,
	`newValue` text,
	`changePercent` decimal(10,2),
	`relatedUrl` text,
	`relatedContentId` int,
	`isRead` boolean DEFAULT false,
	`isDismissed` boolean DEFAULT false,
	`actionTaken` text,
	`actionTakenAt` timestamp,
	`triggeredAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `alertHistory_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitorAlerts` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`competitorId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`alertType` enum('new_content','review_change','rating_change','price_change','subscriber_milestone','engagement_spike','sentiment_shift','keyword_mention','custom') NOT NULL,
	`threshold` int,
	`thresholdType` enum('absolute','percentage'),
	`keywords` json,
	`isEnabled` boolean DEFAULT true,
	`frequency` enum('realtime','daily','weekly') DEFAULT 'daily',
	`lastCheckedAt` timestamp,
	`lastTriggeredAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitorAlerts_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitorYouTubeChannels` (
	`id` int AUTO_INCREMENT NOT NULL,
	`competitorId` int NOT NULL,
	`userId` int NOT NULL,
	`channelId` varchar(64) NOT NULL,
	`channelName` varchar(255) NOT NULL,
	`channelHandle` varchar(64),
	`thumbnailUrl` text,
	`bannerUrl` text,
	`description` text,
	`subscriberCount` bigint,
	`videoCount` int,
	`viewCount` bigint,
	`avgViews` int,
	`avgLikes` int,
	`avgComments` int,
	`engagementRate` decimal(10,4),
	`postingFrequency` varchar(64),
	`topContentTypes` json,
	`topKeywords` json,
	`contentThemes` json,
	`audienceSentiment` enum('very_positive','positive','neutral','negative','very_negative'),
	`sentimentBreakdown` json,
	`topAudienceComplaints` json,
	`topAudiencePraises` json,
	`historicalMetrics` json,
	`lastAnalyzedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitorYouTubeChannels_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `youtubeChannelComparisons` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`description` text,
	`channelIds` json NOT NULL,
	`metricsComparison` json,
	`contentOverlap` json,
	`audienceComparison` json,
	`winner` int,
	`winnerReason` text,
	`recommendations` text,
	`opportunities` json,
	`threats` json,
	`aiInsights` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `youtubeChannelComparisons_id` PRIMARY KEY(`id`)
);
