CREATE TABLE `competitorContentCalendar` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`competitorId` int NOT NULL,
	`competitorContentId` int,
	`title` varchar(512) NOT NULL,
	`contentType` enum('blog_post','video','podcast','social_post','ad','landing_page','email','webinar','case_study','whitepaper','product_launch','event','other') NOT NULL,
	`url` text,
	`thumbnailUrl` text,
	`publishedAt` timestamp NOT NULL,
	`dayOfWeek` int,
	`hourOfDay` int,
	`views` int,
	`likes` int,
	`comments` int,
	`shares` int,
	`engagementRate` decimal(10,4),
	`topics` json,
	`sentiment` enum('positive','neutral','negative'),
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitorContentCalendar_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `competitorReports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`title` varchar(255) NOT NULL,
	`reportType` enum('weekly_summary','monthly_summary','quarterly_review','competitor_deep_dive','market_overview','custom') NOT NULL,
	`competitorIds` json,
	`sections` json,
	`executiveSummary` text,
	`keyFindings` json,
	`recommendations` json,
	`metricsSnapshot` json,
	`swotAnalysis` json,
	`pdfUrl` text,
	`pdfSize` int,
	`scheduleId` int,
	`isScheduled` boolean DEFAULT false,
	`status` enum('generating','completed','failed') DEFAULT 'generating',
	`errorMessage` text,
	`emailDelivered` boolean DEFAULT false,
	`emailDeliveredAt` timestamp,
	`emailRecipients` json,
	`generatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `competitorReports_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `postingPatterns` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`competitorId` int NOT NULL,
	`avgPostsPerWeek` decimal(5,2),
	`avgPostsPerMonth` decimal(5,2),
	`bestDayOfWeek` int,
	`bestHourOfDay` int,
	`dayDistribution` json,
	`hourDistribution` json,
	`contentTypeDistribution` json,
	`contentGaps` json,
	`recommendations` json,
	`analyzedFrom` timestamp,
	`analyzedTo` timestamp,
	`contentCount` int,
	`analyzedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `postingPatterns_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `reportSchedules` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`name` varchar(255) NOT NULL,
	`reportType` enum('weekly_summary','monthly_summary','quarterly_review','competitor_deep_dive','market_overview','custom') NOT NULL,
	`competitorIds` json,
	`frequency` enum('weekly','biweekly','monthly','quarterly') NOT NULL,
	`dayOfWeek` int,
	`dayOfMonth` int,
	`timeOfDay` varchar(8),
	`timezone` varchar(64) DEFAULT 'UTC',
	`emailEnabled` boolean DEFAULT true,
	`emailRecipients` json,
	`includeSections` json,
	`customPrompt` text,
	`status` enum('active','paused','completed') DEFAULT 'active',
	`lastRunAt` timestamp,
	`nextRunAt` timestamp,
	`runCount` int DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `reportSchedules_id` PRIMARY KEY(`id`)
);
